// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertOrderItems implements pgx.CopyFromSource.
type iteratorForInsertOrderItems struct {
	rows                 []InsertOrderItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertOrderItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertOrderItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].Sku,
		r.rows[0].Quantity,
		r.rows[0].UnitPriceCents,
	}, nil
}

func (r iteratorForInsertOrderItems) Err() error {
	return nil
}

func (q *Queries) InsertOrderItems(ctx context.Context, arg []InsertOrderItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_items"}, []string{"order_id", "sku", "quantity", "unit_price_cents"}, &iteratorForInsertOrderItems{rows: arg})
}
