// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Order struct {
	ID         int64
	UserID     int64
	TotalCents int64
	CreatedAt  time.Time
}

type OrderIdempotencyKey struct {
	UserID      int64
	Key         string
	RequestHash string
	OrderID     int64
	CreatedAt   time.Time
}

type OrderItem struct {
	ID             int64
	OrderID        int64
	Sku            string
	Quantity       int32
	UnitPriceCents int64
}

type User struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt time.Time
}
