// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id)
VALUES ($1)
RETURNING id, user_id, total_cents, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, userID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, userID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}

type InsertOrderItemsParams struct {
	OrderID        int64
	Sku            string
	Quantity       int32
	UnitPriceCents int64
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, total_cents, created_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2::bigint
`

type ListOrdersParams struct {
	UserID   int64
	RowLimit int64
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersAfter = `-- name: ListOrdersAfter :many
SELECT id, user_id, total_cents, created_at
FROM orders
WHERE user_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $4::bigint
`

type ListOrdersAfterParams struct {
	UserID         int64
	AfterCreatedAt time.Time
	AfterID        int64
	RowLimit       int64
}

func (q *Queries) ListOrdersAfter(ctx context.Context, arg ListOrdersAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersAfter,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderTotal = `-- name: UpdateOrderTotal :one
UPDATE orders
SET total_cents = (
    SELECT coalesce(sum(i.quantity * i.unit_price_cents), 0)
    FROM order_items i
    WHERE i.order_id = orders.id
)
WHERE orders.id = $1
RETURNING id, user_id, total_cents, created_at
`

func (q *Queries) UpdateOrderTotal(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderTotal, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalCents,
		&i.CreatedAt,
	)
	return i, err
}
